### ISSUE TITLE
Unwrapping and Expecting causes GUI applications to crash

### ISSUE THREAD

**Issue by mmstick** [dbr/tvdb-rs#1]
I'm using this crate in a [GTK3 application](https://github.com/mmstick/tv-renamer) at the moment and it would seem that if this crate has a problem, instead of passing up an error that my application can handle, it's crashing the GUI because of the use of unwrap() or expect(). It's probably not a good idea for a library to ever use these functions.

**Comment by dbr** [comment]
Excuse the very belated reply! Interesting looking project!

You are completely right - I am using this library to slowly learn Rust, and the error handling is something I was(/am) still getting used to, so I put the unwraps in as a placeholder until I worked out how to do better error returning

I've just released `v0.3.1` which should have better error handling - particularly for the common case of HTTP errors form TVDB and malformed XML

There is still a few more expect's to get rid of (mainly on the fields the API described as "cannot be null" - I suspect it's probably a good idea to make more of these `Option`s in the API instead of trusting the API will _always_ populate these)

**Comment by mmstick** [comment]
If you need any help, I can offer a hand.

**Comment by dbr** [comment]
I've removed the last of the unwrap/expect's I think - any thoughts on the error handling (or code in general really) would be appreciated!

**Comment by dbr** [comment]
Released 0.4.0 which should no longer panic

**Comment by mmstick** [comment]
Thanks. I'll be trying it out soon.
